# Generated by Django 6.1 on 2026-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
